[package]
name = "cgraph"
version = "0.1.0"
authors = ["Celdir <michael.earl7769@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
